### ISSUE TITLE
ValueError: not enough values to unpack (expected 10, got 0)

### ISSUE THREAD

**Issue by MitchOkabe** [dvruette/sd-webui-fabric#11]
I seem to be getting an error, and I don't see any activity in the FABRIC V0.3.4 section of txt2img. I've set the batch size to 4, and left the rest of SD and FABRIC parameters to default. In the console I see the following error:

Error running process: E:\stable-diffusion-webui\extensions\sd-webui-fabric\scripts\fabric.py
Traceback (most recent call last):
  File "E:\stable-diffusion-webui\modules\scripts.py", line 386, in process
    script.process(p, *script_args)
  File "E:\stable-diffusion-webui\extensions\sd-webui-fabric\scripts\fabric.py", line 242, in process
    (
ValueError: not enough values to unpack (expected 10, got 0)

Though, the load bars do have this line as well "[FABRIC] Restoring original U-Net forward pass".

**Comment by dvruette** [comment]
This is puzzling me a bit, it almost seems like the FABRIC plugin is not loading. Can you share which version of the WebUI you're using? Also, any other plugins active?

**Comment by MitchOkabe** [comment]
That was with no other 3rd party plugins and using this commit https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/0cc0ee1bcb4c24a8c9715f66cede06601bfc00c8.

But it looks like the WebUI version was the culprit. After updating to the latest, it works!
