### ISSUE TITLE
Runtime Error

### ISSUE THREAD

**Issue by K3nt3L** [dvruette/sd-webui-fabric#12]
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument mat1 in method wrapper_CUDA_addmm)
Time taken: 1.53sTorch active/reserved: 1714/2282 MiB, Sys VRAM: 4267/8192 MiB (52.09%)

WebUI clean install :
After a batch, I can't run anything new. I need to restart the UI for new generations.

**Comment by dvruette** [comment]
Can you provide a bit more information about the inputs/settings? Is it possible you're using low-VRAM settings or something the like?

**Comment by SidAbhi** [comment]
Having the same issue, my launch commands are --medvram --opt-sdp-attention --api, adding any image to like or dislike creates this error. Removing medvram seems to fix it, but would be nice to make it work with it.

**Comment by dvruette** [comment]
Ok yes that's not entirely unexpected. I'll see if I can fix it.

**Comment by dvruette** [comment]
Should be fixed in the newest version.
