### ISSUE TITLE
Not all params used for inference

### ISSUE THREAD

**Issue by catboxanon** [dvruette/sd-webui-fabric#13]
Several paremeters such as `Min. weight`, `Max. weight`, and `Neg. scale` are currently not used anywhere, except for in [`use_feedback`](https://github.com/dvruette/sd-webui-fabric/blob/10e76b321e1da8581fcc6bc011cf7ffee4a2c4f2/scripts/fabric.py#L36), which is only to enable/disable functionality as a whole. As such, they never affect the output. I'm guessing this is functionality that is not yet implemented and planned to be, but I'm opening this issue on the off chance it was missed somehow.

**Comment by dvruette** [comment]
You’re right, I did in fact forget about this haha. But I’ll definitely add the functionality, thanks for the reminder.

**Comment by dvruette** [comment]
Should be fixed now.
