### ISSUE TITLE
Please release a Easy Diffusion version of this plugin

### ISSUE THREAD

**Issue by CHJ85** [dvruette/sd-webui-fabric#19]
Hi there. Could you please release this plugin for Easy Diffusion?
If you don't know, ED is the new kid on the block and is already starting to take a lead on A1111, and are in some cases better than Automatic1111, especially if you enable the plugins and the beta features, ControlNet and such.
Anyway. please consider it. Thank you.

**Comment by dvruette** [comment]
I’m not familiar with EasyDiffusion, and unfortunately I don’t currently have capacity to look into it, but this repository could serve as a good starting point for such a plugin.

**Comment by CHJ85** [comment]
Thanks. Easy Diffusion is sorta new to the scene but growing fast in popularity.
Btw. If you're interested, Easy Diffusion plugins use Javascript as their scripting language.
Here's an example of a LoRA control plugin: https://github.com/patriceac/Easy-Diffusion-Plugins/blob/main/plugins/The_Stig/stigs-lora-shuttle-controls.plugin.js.
I'm not a programmer myself though.
