### ISSUE TITLE
    UnboundLocalError: local variable 'pos_latents' referenced before assignment

### ISSUE THREAD

**Issue by matrix4767** [dvruette/sd-webui-fabric#2]
Error running process: G:\stable-webui\extensions\sd-webui-fabric\scripts\fabric.py
    Traceback (most recent call last):
      File "G:\stable-webui\modules\scripts.py", line 474, in process
        script.process(p, *script_args)
      File "G:\stable-webui\extensions\sd-webui-fabric\scripts\fabric.py", line 269, in process
        pos_latents=pos_latents,
    UnboundLocalError: local variable 'pos_latents' referenced before assignment

**Comment by Enferlain** [comment]
Same, thoughts?

![image](https://github.com/dvruette/sd-webui-fabric/assets/15861396/0197d799-8e33-4f51-b5c7-5151dfe38819)

**Comment by Enferlain** [comment]
seems like it got broken in the last commit, dunno by what tho

**Comment by dvruette** [comment]
Yeah that's my bad for pushing "minor fixes" without actually testing it. Should be fixed now.
