### ISSUE TITLE
Possibility to release Fabric as ComfyUI node for SDXL model?

### ISSUE THREAD

**Issue by morganavr** [dvruette/sd-webui-fabric#20]
It would be great if somebody did it. ComfyUI at the moment is the best choice to run SDXL models/Loras.

**Comment by dvruette** [comment]
Contributions are very welcome, as I currently don’t have capacity to look into it myself. The code in this repo should serve as a good starting point.

**Comment by ssitu** [comment]
Here's my attempt: https://github.com/ssitu/ComfyUI_fabric

The results look different but similar to what you get on the sd-webui. The differences might just be from how things are done differently behind the scenes in the two UIs.
