### ISSUE TITLE
Negative weights not passed to weighted attention

### ISSUE THREAD

**Issue by ssitu** [dvruette/sd-webui-fabric#26]
I was looking through the code and saw that the negative weights `ws` are not passed to the weighted attention function. Is this correct?

https://github.com/dvruette/sd-webui-fabric/blob/8529e075c7ea3bd081de7f0d456cf6ec5ca1e3e4/scripts/patching.py#L186

**Comment by dvruette** [comment]
You're absolutely right, nice catch!
