### ISSUE TITLE
RuntimeError: Given groups=1, weight of size [320, 9, 3, 3], expected input[1, 4, 64, 64] to have 9 channels, but got 4 channels instead

### ISSUE THREAD

**Issue by Oem42** [dvruette/sd-webui-fabric#32]
When I run I get 
RuntimeError: Given groups=1, weight of size [320, 9, 3, 3], expected input[1, 4, 64, 64] to have 9 channels, but got 4 channels instead

im using an inpainting model in img2img mode, is this supported?

**Comment by dvruette** [comment]
Thanks for opening an issue! I have personally never tested inpainting with FABRIC so I wouldn’t be surprised if it wasn’t compatible.. In fact the error message suspiciously looks as if it wasn’t. I’ve tested regular img2img which did work, so if you’re getting the same error there then it might be something else underlying both.
