### ISSUE TITLE
meta data

### ISSUE THREAD

**Issue by webtv123** [dvruette/sd-webui-fabric#36]
if you got a low end graphics card the more images you add and you save the preset the slower it will bog down your computer. And do not load any images through the PNG info or the browsers to send to text to image because it will load all the presets that you save and it will bog down your computer.  My fix was to remove all the images and DELETE the folder that it created And not UNINSTALL... And if you do decide to use the plug-in try using very few images

**Comment by dvruette** [comment]
Thanks for raising this issue! It seems like this could indeed be an issue once the number of cached feedback images gets too large…

In order to find a fix that works for you, approximately how many images are we talking about? I’ll take a look at this once I have time to work on FABRIC again.

**Comment by webtv123** [comment]
on rtx 3060 12 gb vram just a few images like 6 on rtx 3090 ti 24 gb of vram maybe about 10 images before it starts lagging

**Comment by dvruette** [comment]
Ok, just so I understand correctly, are you using the presets feature for saving/loading FABRIC presets? If not, then I think that what you’re talking about is just FABRIC using more resources the more feedback images you add. When loading images from the “PNG info” tab that were generated with FABRIC, FABRIC automatically loads the same feedback images again and sets itself to “Enabled”. To prevent slowing down future generations, simply disable FABRIC. No need to delete the cache folder.
