### ISSUE TITLE
Non-square images are squashed in likes and dislikes

### ISSUE THREAD

**Issue by Gushousekai195** [dvruette/sd-webui-fabric#5]
Whenever an image that has non-square dimensions is put into the likes or dislikes, the image is squashed, affecting the appearance of the image and also the subsequent generations.

**Comment by matrix4767** [comment]
I thought that was just a visual thing. Guess that's why outputs got messy compared to controlnet reference even.

**Comment by dvruette** [comment]
Indeed, there was a bug in the resizing code which caused the aspect ratios to get messed up. Should be fixed in the latest version (both appearance in the like/dislike gallery as well as effect on the generated images).
