### ISSUE TITLE
Feedback images don't seem to have any effect on subsequent generations on some models

### ISSUE THREAD

**Issue by Gushousekai195** [dvruette/sd-webui-fabric#6]
I've noticed that no matter how many images I dislike or like, the generations afterwards do not get better. Even if I use the same seed and even disable the Fabric extension the generation is still the same!

What is going on here? The HF demo didn't have this problem.

**Comment by Gushousekai195** [comment]
Okay, so I'm observing this behavior when using the absolutereality v1.6 model. But when I use the DreamShaper model like the HF demo does, Fabric works as expected.

What might be causing this?

**Comment by dvruette** [comment]
This should also be fixed in the latest version, tested with absolutereality v1.6 and it seems to work. lmk if it doesn't.
