### ISSUE TITLE
[SUGGESTION] Good good kind person, this needs to be implemented.. (presets saving)

### ISSUE THREAD

**Issue by PurpleBlueAloeVera** [dvruette/sd-webui-fabric#7]
This extension has a shit ton of potential. You're amazing.

Just one thing that I'm craving right now, a preset loader to save images in likes and dislikes, and to load depending on what we want to generate dynamically. 

example if I make presents in likes and dislikes for landscapes, I want to be able to click on "presets" "landscapes" and it'll load the feedback images I've saved in that preset.

pleeeeeeeeease can this happen ? <3 Thanks for you work !

**Comment by dvruette** [comment]
Sounds like a great idea and an awesome feature to have. Right now I’m kind of limited on time, but I’d be thrilled to have someone else pick up this issue and submit a PR.

**Comment by dvruette** [comment]
I've added basic functionality for saving/loading presets in the most recent update. Try it out and let me know if there's any way it can be improved, feedback is appreciated.
