### ISSUE TITLE
[ISSUE] - Images brought in feedback, seem to remain in cache somehow. Even after clearing. Which forces a restart

### ISSUE THREAD

**Issue by PurpleBlueAloeVera** [dvruette/sd-webui-fabric#8]
Even after clearing the images. When generating, it still slowed the whole generation process down as if the images were still in feedback. So they must be stuck in cache or something. mmh

**Comment by zethfoxster** [comment]
![image](https://github.com/dvruette/sd-webui-fabric/assets/5951657/18412d95-990e-4657-b981-9a5a0c0af645)
i can confirm this too

**Comment by dvruette** [comment]
I'm having trouble reproducing this issue. Could you provide some steps to reproduce? Are you using any CLI options? And how much slow down are we talking, in seconds?

**Comment by dvruette** [comment]
Hmm, that is weird indeed. Can you try updating to the new version and see if it still happens? It should now tell you exactly how many/which feedback images were used when you select an image (where it usually shows generation params like seed, cfg scale, etc.)

**Comment by zethfoxster** [comment]
theres  more than one issue here...i personally don't have the massive slow down everytime...but in the picture i posted, this is the effects of imgs stuck in the cache, I disabled the lora that creates that character and i get this, the character in rainbow lighting....

**Comment by dvruette** [comment]
So it happens after you disable LoRA? That might have something to do with it, it’s possible that the old U-Net forward pass doesn’t get restored correctly, which would have the observed effect.

**Comment by PurpleBlueAloeVera** [comment]
Happened to me even without any LoRAs.
Could it be embeddings ?? I use my own trained embeddings all the time...
